name: ci

on:
  push:
    branches:
      - 'main'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: unicorn_user
          POSTGRES_PASSWORD: magical_password
          POSTGRES_DB: calendso
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./docker
          push: false
          tags: test/calcom:latest
          network: host
          build-args: |
            NEXT_PUBLIC_WEBAPP_URL=http://localhost:3000
            NEXT_PUBLIC_LICENSE_CONSENT=agree
            CALCOM_TELEMETRY_DISABLED=1
            NEXTAUTH_SECRET=secret
            CALENDSO_ENCRYPTION_KEY=secret
            DATABASE_URL=postgresql://unicorn_user:magical_password@postgres:5432/calendso
            DATABASE_DIRECT_URL=postgresql://unicorn_user:magical_password@postgres:5432/calendso
