name: Update Submodules

on:
  schedule:
    - cron: "0 5 * * *"
  workflow_dispatch: ~

jobs:
  sync:
    name: 'Submodules Sync'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Get Token
        id: get_workflow_token
        uses: peter-murray/workflow-application-token-action@v3
        with:
          application_id: ${{ secrets.APPLICATION_ID }}
          application_private_key: ${{ secrets.APPLICATION_PRIVATE_KEY }}
          revoke_token: true

      - name: Git submodule update
        run: |
          git submodule update --remote --init

      - name: Commit
        env:
          GITHUB_TOKEN: ${{ steps.get_workflow_token.outputs.token }}
        run: |
          git config user.email "actions@github.com"
          git config user.name "actions-user"
          git commit -am "Auto updated submodule references" && git push || echo "No changes to commit"
